name: test on PR

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test the project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test
